# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import individualdiscount_pb2 as individualdiscount__pb2


class DiscountStub(object):
  """The individual discount service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.IndividualDiscount = channel.unary_unary(
        '/individualdiscount.Discount/IndividualDiscount',
        request_serializer=individualdiscount__pb2.IndividualDiscountRequest.SerializeToString,
        response_deserializer=individualdiscount__pb2.IndividualDiscountReply.FromString,
        )


class DiscountServicer(object):
  """The individual discount service definition.
  """

  def IndividualDiscount(self, request, context):
    """Sends a discount
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DiscountServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'IndividualDiscount': grpc.unary_unary_rpc_method_handler(
          servicer.IndividualDiscount,
          request_deserializer=individualdiscount__pb2.IndividualDiscountRequest.FromString,
          response_serializer=individualdiscount__pb2.IndividualDiscountReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'individualdiscount.Discount', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
